trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Stage 1: Build
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: UseNode@1
      inputs:
        version: '14.x'
    
    - script: |
        npm install
        npm run build
      displayName: 'Install Dependencies and Build'

# Stage 2: Test
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - task: UseNode@1
      inputs:
        version: '14.x'
    
    - script: |
        npm install
        npm run test -- --ci --reporters=jest-junit
      displayName: 'Run Unit Tests'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/TEST-*.xml'
        testRunTitle: 'Frontend Unit Tests'

# Stage 3: Deploy
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy Job'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to Staging Environment"
            displayName: 'Deploy to Staging'
            # Here, you would include actual deployment steps such as containerization, kubectl commands, or Azure Web App deployment steps.
